using MemoryPalaceAPI.Models.TwoDigitSystemModels;
using Swashbuckle.AspNetCore.Filters;

namespace MemoryPalaceAPI.Swagger.Examples
{
    public class CreateTwoDigitSystemDtoExample : IExamplesProvider<CreateTwoDigitSystemDto>
    {

        public CreateTwoDigitSystemDto GetExamples()
        {
            return new CreateTwoDigitSystemDto()
            {
                TwoDigitElements = new List<TwoDigitElementDto>()
                    {
                        new TwoDigitElementDto { Number = "00", Text = "tree" },
                        new TwoDigitElementDto { Number = "01", Text = "car" },
                        new TwoDigitElementDto { Number = "02", Text = "superman" },
                        new TwoDigitElementDto { Number = "03", Text = "bonfire" },
                        new TwoDigitElementDto { Number = "04", Text = "Vader" },
                        new TwoDigitElementDto { Number = "05", Text = "iron" },
                        new TwoDigitElementDto { Number = "06", Text = "sword" },
                        new TwoDigitElementDto { Number = "07", Text = "crown" },
                        new TwoDigitElementDto { Number = "08", Text = "dog" },
                        new TwoDigitElementDto { Number = "09", Text = "zombie" },
                        new TwoDigitElementDto { Number = "10", Text = "swing" },
                        new TwoDigitElementDto { Number = "11", Text = "chandelier" },
                        new TwoDigitElementDto { Number = "12", Text = "moon" },
                        new TwoDigitElementDto { Number = "13", Text = "smartphone" },
                        new TwoDigitElementDto { Number = "14", Text = "Xardas" },
                        new TwoDigitElementDto { Number = "15", Text = "bear" },
                        new TwoDigitElementDto { Number = "16", Text = "chain" },
                        new TwoDigitElementDto { Number = "17", Text = "stone" },
                        new TwoDigitElementDto { Number = "18", Text = "table" },
                        new TwoDigitElementDto { Number = "19", Text = "frying pan" },
                        new TwoDigitElementDto { Number = "20", Text = "priest" },
                        new TwoDigitElementDto { Number = "21", Text = "fern" },
                        new TwoDigitElementDto { Number = "22", Text = "knight" },
                        new TwoDigitElementDto { Number = "23", Text = "spider" },
                        new TwoDigitElementDto { Number = "24", Text = "gun" },
                        new TwoDigitElementDto { Number = "25", Text = "paper newspaper" },
                        new TwoDigitElementDto { Number = "26", Text = "Arnold Schwarzenegger" },
                        new TwoDigitElementDto { Number = "27", Text = "Picture" },
                        new TwoDigitElementDto { Number = "28", Text = "Flying carpet" },
                        new TwoDigitElementDto { Number = "29", Text = "Octopus" },
                        new TwoDigitElementDto { Number = "30", Text = "Scooter" },
                        new TwoDigitElementDto { Number = "31", Text = "Dumbbell" },
                        new TwoDigitElementDto { Number = "32", Text = "Map" },
                        new TwoDigitElementDto { Number = "33", Text = "Santa Claus" },
                        new TwoDigitElementDto { Number = "34", Text = "Helicopter" },
                        new TwoDigitElementDto { Number = "35", Text = "Cactus" },
                        new TwoDigitElementDto { Number = "36", Text = "Judo" },
                        new TwoDigitElementDto { Number = "37", Text = "Butterfly" },
                        new TwoDigitElementDto { Number = "38", Text = "Lava" },
                        new TwoDigitElementDto { Number = "39", Text = "Mosquito" },
                        new TwoDigitElementDto { Number = "40", Text = "Stork" },
                        new TwoDigitElementDto { Number = "41", Text = "laptop" },
                        new TwoDigitElementDto { Number = "42", Text = "ball" },
                        new TwoDigitElementDto { Number = "43", Text = "earthworm" },
                        new TwoDigitElementDto { Number = "44", Text = "egg" },
                        new TwoDigitElementDto { Number = "45", Text = "perfume" },
                        new TwoDigitElementDto { Number = "46", Text = "swimming pool (in the garden)" },
                        new TwoDigitElementDto { Number = "47", Text = "Protein Shake (bottle)" },
                        new TwoDigitElementDto { Number = "48", Text = "coffee in a cup" },
                        new TwoDigitElementDto { Number = "49", Text = "Shrek" },
                        new TwoDigitElementDto { Number = "50", Text = "book" },
                        new TwoDigitElementDto { Number = "51", Text = "tank" },
                        new TwoDigitElementDto { Number = "52", Text = "motorcycle" },
                        new TwoDigitElementDto { Number = "53", Text = "chimpanzee" },
                        new TwoDigitElementDto { Number = "54", Text = "hammer" },
                        new TwoDigitElementDto { Number = "55", Text = "thermometer" },
                        new TwoDigitElementDto { Number = "56", Text = "sock" },
                        new TwoDigitElementDto { Number = "57", Text = "Moses" },
                        new TwoDigitElementDto { Number = "58", Text = "palette" },
                        new TwoDigitElementDto { Number = "59", Text = "website" },
                        new TwoDigitElementDto { Number = "60", Text = "Saturn" },
                        new TwoDigitElementDto { Number = "61", Text = "galoshes" },
                        new TwoDigitElementDto { Number = "62", Text = "solar panel" },
                        new TwoDigitElementDto { Number = "63", Text = "hat" },
                        new TwoDigitElementDto { Number = "64", Text = "Dr. House" },
                        new TwoDigitElementDto { Number = "65", Text = "Garfield" },
                        new TwoDigitElementDto { Number = "66", Text = "airplane" },
                        new TwoDigitElementDto { Number = "67", Text = "wallet" },
                        new TwoDigitElementDto { Number = "68", Text = "Mona Lisa" },
                        new TwoDigitElementDto { Number = "69", Text = "bus" },
                        new TwoDigitElementDto { Number = "70", Text = "skeleton (living, scary)" },
                        new TwoDigitElementDto { Number = "71", Text = "bachelor's thesis" },
                        new TwoDigitElementDto { Number = "72", Text = "Steve from Minecraft" },
                        new TwoDigitElementDto { Number = "73", Text = "ship" },
                        new TwoDigitElementDto { Number = "74", Text = "geyser" },
                        new TwoDigitElementDto { Number = "75", Text = "guitar" },
                        new TwoDigitElementDto { Number = "76", Text = "lemon" },
                        new TwoDigitElementDto { Number = "77", Text = "knot" },
                        new TwoDigitElementDto { Number = "78", Text = "Job" },
                        new TwoDigitElementDto { Number = "79", Text = "tablets" },
                        new TwoDigitElementDto { Number = "80", Text = "pâté" },
                        new TwoDigitElementDto { Number = "81", Text = "fireworks" },
                        new TwoDigitElementDto { Number = "82", Text = "gargoyle" },
                        new TwoDigitElementDto { Number = "83", Text = "bicycle" },
                        new TwoDigitElementDto { Number = "84", Text = "elephant" },
                        new TwoDigitElementDto { Number = "85", Text = "parachute" },
                        new TwoDigitElementDto { Number = "86", Text = "Christmas tree" },
                        new TwoDigitElementDto { Number = "87", Text = "matryoshka" },
                        new TwoDigitElementDto { Number = "88", Text = "fish" },
                        new TwoDigitElementDto { Number = "89", Text = "rubber duck" },
                        new TwoDigitElementDto { Number = "90", Text = "suit" },
                        new TwoDigitElementDto { Number = "91", Text = "Buddha" },
                        new TwoDigitElementDto { Number = "92", Text = "Flag" },
                        new TwoDigitElementDto { Number = "93", Text = "Jar" },
                        new TwoDigitElementDto { Number = "94", Text = "Pants" },
                        new TwoDigitElementDto { Number = "95", Text = "Throne" },
                        new TwoDigitElementDto { Number = "96", Text = "Frog" },
                        new TwoDigitElementDto { Number = "97", Text = "Banana" },
                        new TwoDigitElementDto { Number = "98", Text = "Popcorn" },
                        new TwoDigitElementDto { Number = "99", Text = "hussar" }
                    }
            };
        }
    
    }
}
