using MemoryPalaceAPI.Entities;
using Microsoft.EntityFrameworkCore;

namespace MemoryPalaceAPI.Seeders
{
    public class MemoryPalaceSeeder
    {
        private readonly MemoryPalaceDbContext _dbContext;

        public MemoryPalaceSeeder(MemoryPalaceDbContext dbContext)
        {
            _dbContext= dbContext;
        }

        public void Seed()
        {
            if (_dbContext.Database.CanConnect())
            {
                if (!_dbContext.Roles.Any())
                {
                    var roles = GetRoles();
                    _dbContext.Roles.AddRange(roles);
                    _dbContext.SaveChanges();
                }

                if (!_dbContext.TwoDigitSystems.Any())
                {
                    var twoDigitSystems = GetTwoDigitSystems();
                    _dbContext.TwoDigitSystems.AddRange(twoDigitSystems);
                    _dbContext.SaveChanges();
                }
            }
        }
        private IEnumerable<Role> GetRoles()
        {
            var roles = new List<Role>()
            {
                new Role()
                {
                    Name = "User"
                },
                new Role()
                {
                Name = "Manager"
            },
                new Role()
                {
                    Name = "Admin"
                },
            };

            return roles;
        }
        private IEnumerable<TwoDigitSystem> GetTwoDigitSystems()
        {
            
            var twoDigitSystems = new List<TwoDigitSystem>()
            {
                new TwoDigitSystem(){
                    TwoDigitElements = new List<TwoDigitElement>()
                    {
                        new TwoDigitElement { Number = "00", Text = "drzewo" },
                        new TwoDigitElement { Number = "01", Text = "samochód" },
                        new TwoDigitElement { Number = "02", Text = "superman" },
                        new TwoDigitElement { Number = "03", Text = "ognisko" },
                        new TwoDigitElement { Number = "04", Text = "Vader" },
                        new TwoDigitElement { Number = "05", Text = "żelazko" },
                        new TwoDigitElement { Number = "06", Text = "miecz" },
                        new TwoDigitElement { Number = "07", Text = "korona" },
                        new TwoDigitElement { Number = "08", Text = "pies" },
                        new TwoDigitElement { Number = "09", Text = "zombie" },
                        new TwoDigitElement { Number = "10", Text = "huśtawka" },
                        new TwoDigitElement { Number = "11", Text = "żyrandol" },
                        new TwoDigitElement { Number = "12", Text = "księżyc" },
                        new TwoDigitElement { Number = "13", Text = "smartphone" },
                        new TwoDigitElement { Number = "14", Text = "Xardas" },
                        new TwoDigitElement { Number = "15", Text = "niedźwiedź" },
                        new TwoDigitElement { Number = "16", Text = "łańcuch" },
                        new TwoDigitElement { Number = "17", Text = "kamień" },
                        new TwoDigitElement { Number = "18", Text = "stół" },
                        new TwoDigitElement { Number = "19", Text = "patelnia" },
                        new TwoDigitElement { Number = "20", Text = "ksiądz" },
                        new TwoDigitElement { Number = "21", Text = "paprotka" },
                        new TwoDigitElement { Number = "22", Text = "rycerz" },
                        new TwoDigitElement { Number = "23", Text = "pająk" },
                        new TwoDigitElement { Number = "24", Text = "pistolet" },
                        new TwoDigitElement { Number = "25", Text = "papierowa gazeta" },
                        new TwoDigitElement { Number = "26", Text = "Arnold Schwarzenegger" },
                        new TwoDigitElement { Number = "27", Text = "Zdjęcie" },
                        new TwoDigitElement { Number = "28", Text = "Latający dywan" },
                        new TwoDigitElement { Number = "29", Text = "Ośmiornica" },
                        new TwoDigitElement { Number = "30", Text = "Hulajnoga" },
                        new TwoDigitElement { Number = "31", Text = "Hantel" },
                        new TwoDigitElement { Number = "32", Text = "Mapa" },
                        new TwoDigitElement { Number = "33", Text = "Święty Mikołaj" },
                        new TwoDigitElement { Number = "34", Text = "Helikopter" },
                        new TwoDigitElement { Number = "35", Text = "Kaktus" },
                        new TwoDigitElement { Number = "36", Text = "Judoga" },
                        new TwoDigitElement { Number = "37", Text = "Motyl" },
                        new TwoDigitElement { Number = "38", Text = "Lawa" },
                        new TwoDigitElement { Number = "39", Text = "Komar" },
                        new TwoDigitElement { Number = "40", Text = "Bocian" },
                        new TwoDigitElement { Number = "41", Text = "laptop" },
                        new TwoDigitElement { Number = "42", Text = "piłka" },
                        new TwoDigitElement { Number = "43", Text = "dżdżownica" },
                        new TwoDigitElement { Number = "44", Text = "jajko" },
                        new TwoDigitElement { Number = "45", Text = "perfum" },
                        new TwoDigitElement { Number = "46", Text = "basen (na ogródek)" },
                        new TwoDigitElement { Number = "47", Text = "Shake białkowy (bidon)" },
                        new TwoDigitElement { Number = "48", Text = "kawa w kubku" },
                        new TwoDigitElement { Number = "49", Text = "Shrek" },
                        new TwoDigitElement { Number = "50", Text = "książka" },
                        new TwoDigitElement { Number = "51", Text = "czołg" },
                        new TwoDigitElement { Number = "52", Text = "motocykl" },
                        new TwoDigitElement { Number = "53", Text = "szympans" },
                        new TwoDigitElement { Number = "54", Text = "młotek" },
                        new TwoDigitElement { Number = "55", Text = "termometr" },
                        new TwoDigitElement { Number = "56", Text = "skarpetka" },
                        new TwoDigitElement { Number = "57", Text = "mojżesz" },
                        new TwoDigitElement { Number = "58", Text = "paleta" },
                        new TwoDigitElement { Number = "59", Text = "strona internetowa" },
                        new TwoDigitElement { Number = "60", Text = "saturn" },
                        new TwoDigitElement { Number = "61", Text = "kalosze" },
                        new TwoDigitElement { Number = "62", Text = "panel słoneczny" },
                        new TwoDigitElement { Number = "63", Text = "kapelusz" },
                        new TwoDigitElement { Number = "64", Text = "dr house" },
                        new TwoDigitElement { Number = "65", Text = "garfield" },
                        new TwoDigitElement { Number = "66", Text = "samolot" },
                        new TwoDigitElement { Number = "67", Text = "portfel" },
                        new TwoDigitElement { Number = "68", Text = "mona lisa" },
                        new TwoDigitElement { Number = "69", Text = "autobus" },
                        new TwoDigitElement { Number = "70", Text = "szkielet (żywy, straszny)" },
                        new TwoDigitElement { Number = "71", Text = "praca licencjacka" },
                        new TwoDigitElement { Number = "72", Text = "steve z minecrafta" },
                        new TwoDigitElement { Number = "73", Text = "statek" },
                        new TwoDigitElement { Number = "74", Text = "gejzer" },
                        new TwoDigitElement { Number = "75", Text = "gitara" },
                        new TwoDigitElement { Number = "76", Text = "cytryna" },
                        new TwoDigitElement { Number = "77", Text = "supeł" },
                        new TwoDigitElement { Number = "78", Text = "hiob" },
                        new TwoDigitElement { Number = "79", Text = "tabletki" },
                        new TwoDigitElement { Number = "80", Text = "pasztet" },
                        new TwoDigitElement { Number = "81", Text = "fajerwerki" },
                        new TwoDigitElement { Number = "82", Text = "gargulec" },
                        new TwoDigitElement { Number = "83", Text = "rower" },
                        new TwoDigitElement { Number = "84", Text = "słoń" },
                        new TwoDigitElement { Number = "85", Text = "spadochron" },
                        new TwoDigitElement { Number = "86", Text = "choinka" },
                        new TwoDigitElement { Number = "87", Text = "matrioszka" },
                        new TwoDigitElement { Number = "88", Text = "ryba" },
                        new TwoDigitElement { Number = "89", Text = "gumowa kaczka" },
                        new TwoDigitElement { Number = "90", Text = "garnitur" },
                        new TwoDigitElement { Number = "91", Text = "Budda" },
                        new TwoDigitElement { Number = "92", Text = "Flaga" },
                        new TwoDigitElement { Number = "93", Text = "Słoik" },
                        new TwoDigitElement { Number = "94", Text = "Spodnie" },
                        new TwoDigitElement { Number = "95", Text = "Tron" },
                        new TwoDigitElement { Number = "96", Text = "Żaba" },
                        new TwoDigitElement { Number = "97", Text = "Banan" },
                        new TwoDigitElement { Number = "98", Text = "Popcorn" },
                        new TwoDigitElement { Number = "99", Text = "husarz" }
                    }
                },
                new TwoDigitSystem()
                {
                    TwoDigitElements = new List<TwoDigitElement>()
                    {
                        new TwoDigitElement { Number = "00", Text = "kot" },
                        new TwoDigitElement { Number = "01", Text = "pomidor" },
                        new TwoDigitElement { Number = "02", Text = "pizza" },
                        new TwoDigitElement { Number = "03", Text = "klawiatura" },
                        new TwoDigitElement { Number = "04", Text = "pingwin" },
                        new TwoDigitElement { Number = "05", Text = "kurtka" },
                        new TwoDigitElement { Number = "06", Text = "banan" },
                        new TwoDigitElement { Number = "07", Text = "laptop" },
                        new TwoDigitElement { Number = "08", Text = "motyl" },
                        new TwoDigitElement { Number = "09", Text = "telewizor" },
                        new TwoDigitElement { Number = "10", Text = "kwiat" },
                        new TwoDigitElement { Number = "11", Text = "pies" },
                        new TwoDigitElement { Number = "12", Text = "gitara" },
                        new TwoDigitElement { Number = "13", Text = "ksiazka" },
                        new TwoDigitElement { Number = "14", Text = "delfin" },
                        new TwoDigitElement { Number = "15", Text = "klucz" },
                        new TwoDigitElement { Number = "16", Text = "słońce" },
                        new TwoDigitElement { Number = "17", Text = "skrzypce" },
                        new TwoDigitElement { Number = "18", Text = "telefon" },
                        new TwoDigitElement { Number = "19", Text = "koń" },
                        new TwoDigitElement { Number = "20", Text = "łódź" },
                        new TwoDigitElement { Number = "21", Text = "książka" },
                        new TwoDigitElement { Number = "22", Text = "jabłko" },
                        new TwoDigitElement { Number = "23", Text = "ręcznik" },
                        new TwoDigitElement { Number = "24", Text = "pociąg" },
                        new TwoDigitElement { Number = "25", Text = "samolot" },
                        new TwoDigitElement { Number = "26", Text = "jednorożec" },
                        new TwoDigitElement { Number = "27", Text = "łóżko" },
                        new TwoDigitElement { Number = "28", Text = "gruszka" },
                        new TwoDigitElement { Number = "29", Text = "traktor" },
                        new TwoDigitElement { Number = "30", Text = "serce" },
                        new TwoDigitElement { Number = "31", Text = "domek" },
                        new TwoDigitElement { Number = "32", Text = "sowa" },
                        new TwoDigitElement { Number = "33", Text = "motocykl" },
                        new TwoDigitElement { Number = "34", Text = "domek" },
                        new TwoDigitElement { Number = "35", Text = "samochód" },
                        new TwoDigitElement { Number = "36", Text = "statek" },
                        new TwoDigitElement { Number = "37", Text = "kotwica" },
                        new TwoDigitElement { Number = "38", Text = "balon" },
                        new TwoDigitElement { Number = "39", Text = "trąbka" },
                        new TwoDigitElement { Number = "40", Text = "krzesło" },
                        new TwoDigitElement { Number = "41", Text = "lampa" },
                        new TwoDigitElement { Number = "42", Text = "żółw" },
                        new TwoDigitElement { Number = "43", Text = "helikopter" },
                        new TwoDigitElement { Number = "44", Text = "komputer" },
                        new TwoDigitElement { Number = "45", Text = "kubek" },
                        new TwoDigitElement { Number = "46", Text = "wazon" },
                        new TwoDigitElement { Number = "47", Text = "papuga" },
                        new TwoDigitElement { Number = "48", Text = "zegar" },
                        new TwoDigitElement { Number = "49", Text = "samolot" },
                        new TwoDigitElement { Number = "50", Text = "motyl" },
                        new TwoDigitElement { Number = "51", Text = "kompas" },
                        new TwoDigitElement { Number = "52", Text = "kuchenka" },
                        new TwoDigitElement { Number = "53", Text = "kosiarka" },
                        new TwoDigitElement { Number = "54", Text = "doniczka" },
                        new TwoDigitElement { Number = "55", Text = "puzzle" },
                        new TwoDigitElement { Number = "56", Text = "łopata" },
                        new TwoDigitElement { Number = "57", Text = "czapka" },
                        new TwoDigitElement { Number = "58", Text = "grill" },
                        new TwoDigitElement { Number = "59", Text = "skateboard" },
                        new TwoDigitElement { Number = "60", Text = "kask" },
                        new TwoDigitElement { Number = "61", Text = "szalik" },
                        new TwoDigitElement { Number = "62", Text = "chusteczka" },
                        new TwoDigitElement { Number = "63", Text = "zamek" },
                        new TwoDigitElement { Number = "64", Text = "konik" },
                        new TwoDigitElement { Number = "65", Text = "skarpeta" },
                        new TwoDigitElement { Number = "66", Text = "klamka" },
                        new TwoDigitElement { Number = "67", Text = "myszka" },
                        new TwoDigitElement { Number = "68", Text = "grzebień" },
                        new TwoDigitElement { Number = "69", Text = "koszula" },
                        new TwoDigitElement { Number = "70", Text = "nożyczki" },
                        new TwoDigitElement { Number = "71", Text = "siekiera" },
                        new TwoDigitElement { Number = "72", Text = "obraz" },
                        new TwoDigitElement { Number = "73", Text = "odkurzacz" },
                        new TwoDigitElement { Number = "74", Text = "latarka" },
                        new TwoDigitElement { Number = "75", Text = "żaba" },
                        new TwoDigitElement { Number = "76", Text = "sernik" },
                        new TwoDigitElement { Number = "77", Text = "śmietnik" },
                        new TwoDigitElement { Number = "78", Text = "parasol" },
                        new TwoDigitElement { Number = "79", Text = "kwiaty" },
                        new TwoDigitElement { Number = "80", Text = "karta" },
                        new TwoDigitElement { Number = "81", Text = "breloczek" },
                        new TwoDigitElement { Number = "82", Text = "kapelusz" },
                        new TwoDigitElement { Number = "83", Text = "kajak" },
                        new TwoDigitElement { Number = "84", Text = "gąbka" },
                        new TwoDigitElement { Number = "85", Text = "drukarka" },
                        new TwoDigitElement { Number = "86", Text = "lornetka" },
                        new TwoDigitElement { Number = "87", Text = "baterie" },
                        new TwoDigitElement { Number = "88", Text = "trójka" },
                        new TwoDigitElement { Number = "89", Text = "zeszyt" },
                        new TwoDigitElement { Number = "90", Text = "koc" },
                        new TwoDigitElement { Number = "91", Text = "szafki" },
                        new TwoDigitElement { Number = "92", Text = "kapcie" },
                        new TwoDigitElement { Number = "93", Text = "sok" },
                        new TwoDigitElement { Number = "94", Text = "myszka" },
                        new TwoDigitElement { Number = "95", Text = "kajdanki" },
                        new TwoDigitElement { Number = "96", Text = "proszek" },
                        new TwoDigitElement { Number = "97", Text = "okulary" },
                        new TwoDigitElement { Number = "98", Text = "sól" },
                        new TwoDigitElement { Number = "99", Text = "pieprz" }
                    }
                },
                new TwoDigitSystem()
                {
                    TwoDigitElements = new List<TwoDigitElement>()
                    {
                        new TwoDigitElement { Number = "00", Text = "tree" },
                        new TwoDigitElement { Number = "01", Text = "car" },
                        new TwoDigitElement { Number = "02", Text = "superman" },
                        new TwoDigitElement { Number = "03", Text = "bonfire" },
                        new TwoDigitElement { Number = "04", Text = "Vader" },
                        new TwoDigitElement { Number = "05", Text = "iron" },
                        new TwoDigitElement { Number = "06", Text = "sword" },
                        new TwoDigitElement { Number = "07", Text = "crown" },
                        new TwoDigitElement { Number = "08", Text = "dog" },
                        new TwoDigitElement { Number = "09", Text = "zombie" },
                        new TwoDigitElement { Number = "10", Text = "swing" },
                        new TwoDigitElement { Number = "11", Text = "chandelier" },
                        new TwoDigitElement { Number = "12", Text = "moon" },
                        new TwoDigitElement { Number = "13", Text = "smartphone" },
                        new TwoDigitElement { Number = "14", Text = "Xardas" },
                        new TwoDigitElement { Number = "15", Text = "bear" },
                        new TwoDigitElement { Number = "16", Text = "chain" },
                        new TwoDigitElement { Number = "17", Text = "stone" },
                        new TwoDigitElement { Number = "18", Text = "table" },
                        new TwoDigitElement { Number = "19", Text = "frying pan" },
                        new TwoDigitElement { Number = "20", Text = "priest" },
                        new TwoDigitElement { Number = "21", Text = "fern" },
                        new TwoDigitElement { Number = "22", Text = "knight" },
                        new TwoDigitElement { Number = "23", Text = "spider" },
                        new TwoDigitElement { Number = "24", Text = "gun" },
                        new TwoDigitElement { Number = "25", Text = "paper newspaper" },
                        new TwoDigitElement { Number = "26", Text = "Arnold Schwarzenegger" },
                        new TwoDigitElement { Number = "27", Text = "Picture" },
                        new TwoDigitElement { Number = "28", Text = "Flying carpet" },
                        new TwoDigitElement { Number = "29", Text = "Octopus" },
                        new TwoDigitElement { Number = "30", Text = "Scooter" },
                        new TwoDigitElement { Number = "31", Text = "Dumbbell" },
                        new TwoDigitElement { Number = "32", Text = "Map" },
                        new TwoDigitElement { Number = "33", Text = "Santa Claus" },
                        new TwoDigitElement { Number = "34", Text = "Helicopter" },
                        new TwoDigitElement { Number = "35", Text = "Cactus" },
                        new TwoDigitElement { Number = "36", Text = "Judo" },
                        new TwoDigitElement { Number = "37", Text = "Butterfly" },
                        new TwoDigitElement { Number = "38", Text = "Lava" },
                        new TwoDigitElement { Number = "39", Text = "Mosquito" },
                        new TwoDigitElement { Number = "40", Text = "Stork" },
                        new TwoDigitElement { Number = "41", Text = "laptop" },
                        new TwoDigitElement { Number = "42", Text = "ball" },
                        new TwoDigitElement { Number = "43", Text = "earthworm" },
                        new TwoDigitElement { Number = "44", Text = "egg" },
                        new TwoDigitElement { Number = "45", Text = "perfume" },
                        new TwoDigitElement { Number = "46", Text = "swimming pool (in the garden)" },
                        new TwoDigitElement { Number = "47", Text = "Protein Shake (bottle)" },
                        new TwoDigitElement { Number = "48", Text = "coffee in a cup" },
                        new TwoDigitElement { Number = "49", Text = "Shrek" },
                        new TwoDigitElement { Number = "50", Text = "book" },
                        new TwoDigitElement { Number = "51", Text = "tank" },
                        new TwoDigitElement { Number = "52", Text = "motorcycle" },
                        new TwoDigitElement { Number = "53", Text = "chimpanzee" },
                        new TwoDigitElement { Number = "54", Text = "hammer" },
                        new TwoDigitElement { Number = "55", Text = "thermometer" },
                        new TwoDigitElement { Number = "56", Text = "sock" },
                        new TwoDigitElement { Number = "57", Text = "Moses" },
                        new TwoDigitElement { Number = "58", Text = "palette" },
                        new TwoDigitElement { Number = "59", Text = "website" },
                        new TwoDigitElement { Number = "60", Text = "Saturn" },
                        new TwoDigitElement { Number = "61", Text = "galoshes" },
                        new TwoDigitElement { Number = "62", Text = "solar panel" },
                        new TwoDigitElement { Number = "63", Text = "hat" },
                        new TwoDigitElement { Number = "64", Text = "Dr. House" },
                        new TwoDigitElement { Number = "65", Text = "Garfield" },
                        new TwoDigitElement { Number = "66", Text = "airplane" },
                        new TwoDigitElement { Number = "67", Text = "wallet" },
                        new TwoDigitElement { Number = "68", Text = "Mona Lisa" },
                        new TwoDigitElement { Number = "69", Text = "bus" },
                        new TwoDigitElement { Number = "70", Text = "skeleton (living, scary)" },
                        new TwoDigitElement { Number = "71", Text = "bachelor's thesis" },
                        new TwoDigitElement { Number = "72", Text = "Steve from Minecraft" },
                        new TwoDigitElement { Number = "73", Text = "ship" },
                        new TwoDigitElement { Number = "74", Text = "geyser" },
                        new TwoDigitElement { Number = "75", Text = "guitar" },
                        new TwoDigitElement { Number = "76", Text = "lemon" },
                        new TwoDigitElement { Number = "77", Text = "knot" },
                        new TwoDigitElement { Number = "78", Text = "Job" },
                        new TwoDigitElement { Number = "79", Text = "tablets" },
                        new TwoDigitElement { Number = "80", Text = "pâté" },
                        new TwoDigitElement { Number = "81", Text = "fireworks" },
                        new TwoDigitElement { Number = "82", Text = "gargoyle" },
                        new TwoDigitElement { Number = "83", Text = "bicycle" },
                        new TwoDigitElement { Number = "84", Text = "elephant" },
                        new TwoDigitElement { Number = "85", Text = "parachute" },
                        new TwoDigitElement { Number = "86", Text = "Christmas tree" },
                        new TwoDigitElement { Number = "87", Text = "matryoshka" },
                        new TwoDigitElement { Number = "88", Text = "fish" },
                        new TwoDigitElement { Number = "89", Text = "rubber duck" },
                        new TwoDigitElement { Number = "90", Text = "suit" },
                        new TwoDigitElement { Number = "91", Text = "Buddha" },
                        new TwoDigitElement { Number = "92", Text = "Flag" },
                        new TwoDigitElement { Number = "93", Text = "Jar" },
                        new TwoDigitElement { Number = "94", Text = "Pants" },
                        new TwoDigitElement { Number = "95", Text = "Throne" },
                        new TwoDigitElement { Number = "96", Text = "Frog" },
                        new TwoDigitElement { Number = "97", Text = "Banana" },
                        new TwoDigitElement { Number = "98", Text = "Popcorn" },
                        new TwoDigitElement { Number = "99", Text = "hussar" }
                    }
                },
                new TwoDigitSystem()
                {
                    TwoDigitElements = new List<TwoDigitElement>()
                    {
                        new TwoDigitElement { Number = "00", Text = "cat" },
                        new TwoDigitElement { Number = "01", Text = "tomato" },
                        new TwoDigitElement { Number = "02", Text = "pizza" },
                        new TwoDigitElement { Number = "03", Text = "keyboard" },
                        new TwoDigitElement { Number = "04", Text = "penguin" },
                        new TwoDigitElement { Number = "05", Text = "jacket" },
                        new TwoDigitElement { Number = "06", Text = "banana" },
                        new TwoDigitElement { Number = "07", Text = "laptop" },
                        new TwoDigitElement { Number = "08", Text = "butterfly" },
                        new TwoDigitElement { Number = "09", Text = "television" },
                        new TwoDigitElement { Number = "10", Text = "flower" },
                        new TwoDigitElement { Number = "11", Text = "dog" },
                        new TwoDigitElement { Number = "12", Text = "guitar" },
                        new TwoDigitElement { Number = "13", Text = "book" },
                        new TwoDigitElement { Number = "14", Text = "dolphin" },
                        new TwoDigitElement { Number = "15", Text = "key" },
                        new TwoDigitElement { Number = "16", Text = "sun" },
                        new TwoDigitElement { Number = "17", Text = "violin" },
                        new TwoDigitElement { Number = "18", Text = "telephone" },
                        new TwoDigitElement { Number = "19", Text = "horse" },
                        new TwoDigitElement { Number = "20", Text = "boat" },
                        new TwoDigitElement { Number = "21", Text = "book" },
                        new TwoDigitElement { Number = "22", Text = "apple" },
                        new TwoDigitElement { Number = "23", Text = "towel" },
                        new TwoDigitElement { Number = "24", Text = "train" },
                        new TwoDigitElement { Number = "25", Text = "airplane" },
                        new TwoDigitElement { Number = "26", Text = "unicorn" },
                        new TwoDigitElement { Number = "27", Text = "bed" },
                        new TwoDigitElement { Number = "28", Text = "pear" },
                        new TwoDigitElement { Number = "29", Text = "tractor" },
                        new TwoDigitElement { Number = "30", Text = "heart" },
                        new TwoDigitElement { Number = "31", Text = "house" },
                        new TwoDigitElement { Number = "32", Text = "owl" },
                        new TwoDigitElement { Number = "33", Text = "motorcycle" },
                        new TwoDigitElement { Number = "34", Text = "house" },
                        new TwoDigitElement { Number = "35", Text = "car" },
                        new TwoDigitElement { Number = "36", Text = "ship" },
                        new TwoDigitElement { Number = "37", Text = "anchor" },
                        new TwoDigitElement { Number = "38", Text = "balloon" },
                        new TwoDigitElement { Number = "39", Text = "trumpet" },
                        new TwoDigitElement { Number = "40", Text = "chair" },
                        new TwoDigitElement { Number = "41", Text = "lamp" },
                        new TwoDigitElement { Number = "42", Text = "turtle" },
                        new TwoDigitElement { Number = "43", Text = "helicopter" },
                        new TwoDigitElement { Number = "44", Text = "computer" },
                        new TwoDigitElement { Number = "45", Text = "mug" },
                        new TwoDigitElement { Number = "46", Text = "vase" },
                        new TwoDigitElement { Number = "47", Text = "parrot" },
                        new TwoDigitElement { Number = "48", Text = "clock" },
                        new TwoDigitElement { Number = "49", Text = "airplane" },
                        new TwoDigitElement { Number = "50", Text = "butterfly" },
                        new TwoDigitElement { Number = "51", Text = "compass" },
                        new TwoDigitElement { Number = "52", Text = "stove" },
                        new TwoDigitElement { Number = "53", Text = "lawnmower" },
                        new TwoDigitElement { Number = "54", Text = "flowerpot" },
                        new TwoDigitElement { Number = "55", Text = "puzzle" },
                        new TwoDigitElement { Number = "56", Text = "shovel" },
                        new TwoDigitElement { Number = "57", Text = "hat" },
                        new TwoDigitElement { Number = "58", Text = "grill" },
                        new TwoDigitElement { Number = "59", Text = "skateboard" },
                        new TwoDigitElement { Number = "60", Text = "helmet" },
                        new TwoDigitElement { Number = "61", Text = "scarf" },
                        new TwoDigitElement { Number = "62", Text = "tissue" },
                        new TwoDigitElement { Number = "63", Text = "castle" },
                        new TwoDigitElement { Number = "64", Text = "pony" },
                        new TwoDigitElement { Number = "65", Text = "sock" },
                        new TwoDigitElement { Number = "66", Text = "handle" },
                        new TwoDigitElement { Number = "67", Text = "mouse" },
                        new TwoDigitElement { Number = "68", Text = "comb" },
                        new TwoDigitElement { Number = "69", Text = "shirt" },
                        new TwoDigitElement { Number = "70", Text = "scissors" },
                        new TwoDigitElement { Number = "71", Text = "axe" },
                        new TwoDigitElement { Number = "72", Text = "picture" },
                        new TwoDigitElement { Number = "73", Text = "vacuum cleaner" },
                        new TwoDigitElement { Number = "74", Text = "flashlight" },
                        new TwoDigitElement { Number = "75", Text = "frog" },
                        new TwoDigitElement { Number = "76", Text = "cheesecake" },
                        new TwoDigitElement { Number = "77", Text = "trash can" },
                        new TwoDigitElement { Number = "78", Text = "umbrella" },
                        new TwoDigitElement { Number = "79", Text = "flowers" },
                        new TwoDigitElement { Number = "80", Text = "card" },
                        new TwoDigitElement { Number = "81", Text = "keychain" },
                        new TwoDigitElement { Number = "82", Text = "hat" },
                        new TwoDigitElement { Number = "83", Text = "kayak" },
                        new TwoDigitElement { Number = "84", Text = "sponge" },
                        new TwoDigitElement { Number = "85", Text = "printer" },
                        new TwoDigitElement { Number = "86", Text = "binoculars" },
                        new TwoDigitElement { Number = "87", Text = "batteries" },
                        new TwoDigitElement { Number = "88", Text = "troika" },
                        new TwoDigitElement { Number = "89", Text = "notebook" },
                        new TwoDigitElement { Number = "90", Text = "blanket" },
                        new TwoDigitElement { Number = "91", Text = "cabinets" },
                        new TwoDigitElement { Number = "92", Text = "slippers" },
                        new TwoDigitElement { Number = "93", Text = "juice" },
                        new TwoDigitElement { Number = "94", Text = "mouse" },
                        new TwoDigitElement { Number = "95", Text = "handcuffs" },
                        new TwoDigitElement { Number = "96", Text = "powder" },
                        new TwoDigitElement { Number = "97", Text = "glasses" },
                        new TwoDigitElement { Number = "98", Text = "salt" },
                        new TwoDigitElement { Number = "99", Text = "pepper" }
                    }
                }
            };

            return twoDigitSystems;
        }
    }
}
